name: Deploy to EC2

on:
  push:
    branches:
      - deploy/#3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          command_timeout: 60m
          script: |
            cd ~/sadollar-kiosk
            git fetch origin
            git reset --hard origin/deploy/#3
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart sadollar
